void ncurses_initialiser()
void ncurses_souris()
int click_souris()
int CHOIX_MODE()
int CHOIX_DIF()
int REJOUER()
int AUREVOIR()
void MUSIQUE()
int** INI_TAB_BI()
void CHARG_MAT_ORDER(int** ORDER_TAB)
void CHARG_MAT_NUM(int** NUM_IN_GAME)
void AFFICH_MAT_ORDER(int** ORDER_TAB)
void AFFICH_MAT_NUM(int** NUM_IN_GAME)
void LIB_MAT_ORDER(int** ORDER_TAB)
void LIB_MAT_NUM(int** NUM_IN_GAME)
int AFFICHE_CHIFFRE_MODE(int** NUM_IN_GAME)
int AFFICHE_IMAGE_MODE(int** NUM_IN_GAME)
int CHIFFRE_MODE_FAC(int** ORDER_TAB, int** NUM_IN_GAME)
int CHIFFRE_MODE_DIF(int** ORDER_TAB, int** NUM_IN_GAME)
int IMAGE_MODE_FAC(int** ORDER_TAB, int** NUM_IN_GAME)
int IMAGE_MODE_DIF(int** ORDER_TAB, int** NUM_IN_GAME)
