struct compression* allouer_arbre(struct compression* comp, struct init_comp* pourquoi);
struct init_comp* creer_arbre(struct init_comp* pourquoi);
int nb_char_dico(char* s);
void init_mat(int** mat, int nbl, int nbc);
void creation_dico(int** dico, int nb_char, char* s);
void tri_dico(int** dico, int nb_char);
void ecrire_mec(int nb, struct arbre* mec, char* s);
void cal_mec(struct arbre* mec, char* s);
void arbre_de_codage(struct init_comp* pourquoi, char* s);
void ecrire_sequence(int* nb, struct lettre* poete, int i, char* s);
void cal_sequence(struct arbre* mec, int* tab , int i, char* s);
void sequence_codee(struct init_comp* pourquoi, char* s);
void fake_tri_dico(int** dico_tri, int nb_char);
void reception_codee(int** bin, int nb_char, char* s);
void compression_bin(int** bin, int nb_char, char* s1, char* s2);
void fichier_compresser(struct init_comp* pourquoi, char* s1, char* s2, char* s3);
struct lettre* al_lettre(int i, int** tab);
struct arbre* al_arbre();
struct compression* recreer_arbre(int** mat, int** tab);
void dechiffre_sequence(int** mat, int** tab, char* s1, char* s2, int nb_char, int bin);